version: 2

sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/conf.py


build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - all

# Don't build any extra formats
formats: []

